- name: Archive Release
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          filename: 'release.zip'
          # 这里指定需要打包的文件和文件夹
          path: 'assets data includes templates .htaccess README.md SECURITY_MIGRATION.md index.php'
